//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PromoCodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRM_PromoCodes()
        {
            this.CRM_Agents = new HashSet<CRM_Agents>();
        }
    
        public long CRM_Promocode_ID { get; set; }
        public string PromoCode { get; set; }
        public string IsActive { get; set; }
        public Nullable<long> GroupNo { get; set; }
        public string Status_ind { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> Createdby { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<long> CRM_Agent_ID { get; set; }
        public string Promocode_Url { get; set; }
        public string ISAdminCode_Ind { get; set; }
        public string ISMultipleUse_Ind { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<System.DateTime> ExpiredOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRM_Agents> CRM_Agents { get; set; }
    }
}
