//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Agent_Incentive_XREF
    {
        public int AgentIncentive_id { get; set; }
        public Nullable<long> CRM_Promocode_ID { get; set; }
        public Nullable<int> Incentive_id { get; set; }
        public string IS_RenewIncentive_Ind { get; set; }
        public string Status_ind { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBY { get; set; }
        public Nullable<System.DateTime> UPdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
