//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBA_FileExecution_SHADOW
    {
        public long FileExecute_ID { get; set; }
        public string Filename { get; set; }
        public int NoOfObjects { get; set; }
        public string IsSQLObject { get; set; }
        public string IsSuccess { get; set; }
        public string CreatedBy { get; set; }
        public string VerifiedBy { get; set; }
        public string ExecutedOn { get; set; }
        public Nullable<System.DateTime> ExecutedDate { get; set; }
        public Nullable<System.DateTime> Shadow_Date { get; set; }
        public string updatedFields { get; set; }
        public long Shadow_id { get; set; }
    }
}
