//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBA_DatabaseEvent_Log_SHADOW
    {
        public int EventLog_ID { get; set; }
        public string LoginName { get; set; }
        public string DatabaseName { get; set; }
        public string EventType { get; set; }
        public string ObjectType { get; set; }
        public string ObjectName { get; set; }
        public string CommandText { get; set; }
        public string HostName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> Shadow_Date { get; set; }
        public string updatedFields { get; set; }
        public long Shadow_id { get; set; }
    }
}
