//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBA_SQLProcedureCall
    {
        public string Procedurename { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string PRCID { get; set; }
    }
}
