//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBA_ScriptErrorLog
    {
        public long ScriptErrorLog_ID { get; set; }
        public long FileExecute_ID { get; set; }
        public string ErrorDesc { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual DBA_FileExecution DBA_FileExecution { get; set; }
    }
}
