//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_Articles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public um_Articles()
        {
            this.um_Article_Authors = new HashSet<um_Article_Authors>();
            this.Ut_Article_Relatedvideos = new HashSet<Ut_Article_Relatedvideos>();
            this.Ut_Article_RelatedArticles = new HashSet<Ut_Article_RelatedArticles>();
        }
    
        public int Article_ID { get; set; }
        public string Title { get; set; }
        public string Article_Desc { get; set; }
        public string Online_Ind { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string ImagePath { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_Article_Authors> um_Article_Authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ut_Article_Relatedvideos> Ut_Article_Relatedvideos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ut_Article_RelatedArticles> Ut_Article_RelatedArticles { get; set; }
    }
}
