//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_Article_Authors
    {
        public long Article_Author_ID { get; set; }
        public Nullable<int> Article_ID { get; set; }
        public Nullable<long> Provider_ID { get; set; }
        public string Provider_Name { get; set; }
        public string PublicURL { get; set; }
        public string Author_Desc { get; set; }
        public string Status_ind { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual um_Articles um_Articles { get; set; }
    }
}
