//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_Billing_Services
    {
        public int BillingService_ID { get; set; }
        public Nullable<int> BillingserviceType_ID { get; set; }
        public string BillingServiceTitle { get; set; }
        public string BillingServiceDescription { get; set; }
        public string IsPracticeService { get; set; }
        public string IsProviderService { get; set; }
        public string IsPatientService { get; set; }
        public string IsDefaultService { get; set; }
        public string IsRenewed { get; set; }
        public string IsUpgradable { get; set; }
        public Nullable<double> ServiceTaxInPercentage { get; set; }
        public string IsThisTaxable { get; set; }
        public string IsProviderRegservice { get; set; }
        public Nullable<int> NoOfSites { get; set; }
        public string Status_Ind { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> RefBillingService_ID { get; set; }
    }
}
