//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_Billing_ServiceTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public um_Billing_ServiceTypes()
        {
            this.um_Billing_ChargeTypes = new HashSet<um_Billing_ChargeTypes>();
        }
    
        public int Billing_ServiceType_ID { get; set; }
        public string ServiceType { get; set; }
        public string Description { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_Billing_ChargeTypes> um_Billing_ChargeTypes { get; set; }
    }
}
