//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_BillingService_ChargeTemplate
    {
        public int BSChargeTemplate_ID { get; set; }
        public int BillingService_ID { get; set; }
        public Nullable<int> BillingChargetype_ID { get; set; }
        public Nullable<int> Billing_ServiceType_ID { get; set; }
        public string Quantity { get; set; }
        public Nullable<decimal> ServiceFee { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual um_Billing_ChargeTypes um_Billing_ChargeTypes { get; set; }
    }
}
