//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_Billing_TransactionTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public um_Billing_TransactionTypes()
        {
            this.ut_Billing_Admin_Transactions = new HashSet<ut_Billing_Admin_Transactions>();
            this.ut_Billing_InvoiceLineItems = new HashSet<ut_Billing_InvoiceLineItems>();
            this.ut_Billing_ProviderPatient_Transactions = new HashSet<ut_Billing_ProviderPatient_Transactions>();
        }
    
        public byte TransactionType_ID { get; set; }
        public string TransactionType { get; set; }
        public string TransactionTypeDescription { get; set; }
        public string Status_Ind { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_Admin_Transactions> ut_Billing_Admin_Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_InvoiceLineItems> ut_Billing_InvoiceLineItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_ProviderPatient_Transactions> ut_Billing_ProviderPatient_Transactions { get; set; }
    }
}
