//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_CreditCardInfo_SHADOW
    {
        public int CreditCardInfo_ID { get; set; }
        public Nullable<byte> ReferenceType_ID { get; set; }
        public Nullable<int> Reference_ID { get; set; }
        public string CreditCardNo { get; set; }
        public Nullable<int> CreditCardType_ID { get; set; }
        public string CVV2 { get; set; }
        public string CardHolderName { get; set; }
        public Nullable<byte> CardExpiryMonth { get; set; }
        public Nullable<short> CardExpiryYear { get; set; }
        public string BillingAddress_1 { get; set; }
        public string BillingAddress_2 { get; set; }
        public Nullable<int> BillingCity_ID { get; set; }
        public Nullable<int> BillingState_ID { get; set; }
        public Nullable<int> BillingCountry_ID { get; set; }
        public string BillingZIP { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string IsDefaultCC_Ind { get; set; }
        public Nullable<System.DateTime> Shadow_Date { get; set; }
        public string updatedFields { get; set; }
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public long Shadow_id { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
        public string practice_ind { get; set; }
        public string paypal_vaultid { get; set; }
    }
}
