//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_Errors
    {
        public int ID { get; set; }
        public Nullable<int> Application_ID { get; set; }
        public string SessionID { get; set; }
        public string RequestMethod { get; set; }
        public string ServerPort { get; set; }
        public string HTTPS { get; set; }
        public string LocalAddr { get; set; }
        public string HostAddress { get; set; }
        public string UserAgent { get; set; }
        public Nullable<int> PageNo { get; set; }
        public string URL { get; set; }
        public string CustomerRefID { get; set; }
        public string FormData { get; set; }
        public string AllHTTP { get; set; }
        public string ErrASPCode { get; set; }
        public string ErrNumber { get; set; }
        public string Exception_Name { get; set; }
        public string ErrSource { get; set; }
        public string ErrCategory { get; set; }
        public string ErrFile { get; set; }
        public Nullable<int> ErrLine { get; set; }
        public Nullable<int> ErrColumn { get; set; }
        public string ErrDescription { get; set; }
        public string ErrAspDescription { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<int> Project_ID { get; set; }
        public string Project_Mode { get; set; }
        public Nullable<int> Class_ID { get; set; }
        public Nullable<int> Method_ID { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Login_Ind { get; set; }
        public string Mobile_Type { get; set; }
        public Nullable<int> Login_id { get; set; }
        public string Name { get; set; }
    }
}
