//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_EmailMessage_Options
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public um_EmailMessage_Options()
        {
            this.um_EmailMessageOption_Body = new HashSet<um_EmailMessageOption_Body>();
        }
    
        public int EmailMessage_Option_ID { get; set; }
        public Nullable<int> Email_OptionType_ID { get; set; }
        public string Message_Title { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UPdatedOn { get; set; }
        public Nullable<long> RefEmailMessage_Option_ID { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
    
        public virtual um_EmailMessageOption_Types um_EmailMessageOption_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_EmailMessageOption_Body> um_EmailMessageOption_Body { get; set; }
    }
}
