//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Um_FAQ_RelatedFaqs
    {
        public long RelatedFaq_Id { get; set; }
        public Nullable<long> ParentFaq_ID { get; set; }
        public Nullable<long> ChildFaq_id { get; set; }
        public string Status_ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Um_FAQ_Questions Um_FAQ_Questions { get; set; }
    }
}
