//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Um_FAQ_Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Um_FAQ_Categories()
        {
            this.Ut_FAQ_Question_category_Xref = new HashSet<Ut_FAQ_Question_category_Xref>();
        }
    
        public int Category_Id { get; set; }
        public string Category_Name { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBY { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ut_FAQ_Question_category_Xref> Ut_FAQ_Question_category_Xref { get; set; }
    }
}
