//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Um_Modules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Um_Modules()
        {
            this.ut_module_field_Xref = new HashSet<ut_module_field_Xref>();
        }
    
        public int Module_id { get; set; }
        public string Modulename { get; set; }
        public string Mod_Description { get; set; }
        public string Status_ind { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_module_field_Xref> ut_module_field_Xref { get; set; }
    }
}
