//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_Provider_Technicians_Xref
    {
        public int Providertech_id { get; set; }
        public Nullable<int> Provider_id { get; set; }
        public Nullable<long> Providerlogin_id { get; set; }
        public Nullable<int> Technician_id { get; set; }
        public string Status_ind { get; set; }
        public Nullable<System.DateTime> createon { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> Updatedby { get; set; }
    
        public virtual um_Provider um_Provider { get; set; }
        public virtual Um_Technician Um_Technician { get; set; }
        public virtual um_User um_User { get; set; }
    }
}
