//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_PublicVideo_SHADOW
    {
        public int PublicVideo_ID { get; set; }
        public string Title { get; set; }
        public string Video_Description { get; set; }
        public string File_Path { get; set; }
        public string Video_path { get; set; }
        public string EncryptedFile_Path { get; set; }
        public string ImagePath { get; set; }
        public string ImagepathSuffix { get; set; }
        public string Online_Ind { get; set; }
        public string Duration { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> Createdby { get; set; }
        public Nullable<System.DateTime> UdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> Shadow_Date { get; set; }
        public string updatedFields { get; set; }
        public long Shadow_id { get; set; }
        public string Youtube_embededtext { get; set; }
        public string Youtube_videoid { get; set; }
    }
}
