//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_Practice_Provider_Patient_XREF
    {
        public int ProviderPatient_ID { get; set; }
        public Nullable<int> Practice_ID { get; set; }
        public Nullable<int> Provider_ID { get; set; }
        public Nullable<long> ProviderLogin_ID { get; set; }
        public Nullable<int> PlaceOfService_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<long> PatientLogin_ID { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MI { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string PatientEmail { get; set; }
        public string DrivingLicenceNo { get; set; }
        public Nullable<int> Patient_Status_ID { get; set; }
        public string SelfRegistered_Ind { get; set; }
        public Nullable<int> AddressType_ID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> City_ID { get; set; }
        public Nullable<int> State_ID { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public string ZIP { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string CellPhone { get; set; }
        public string MobilePhone { get; set; }
        public string PrimaryAddress_Ind { get; set; }
        public Nullable<System.DateTime> RegOndate { get; set; }
        public string IsInPatientEntryCount { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CraetedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Full_name { get; set; }
        public string DCity_Name { get; set; }
        public string DState_Name { get; set; }
        public string DCountry_Name { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public Nullable<int> DefaultCourtLocation_ID { get; set; }
    
        public virtual um_AddressType um_AddressType { get; set; }
        public virtual um_City um_City { get; set; }
        public virtual um_Patient_PersonalInfo um_Patient_PersonalInfo { get; set; }
        public virtual um_Provider um_Provider { get; set; }
        public virtual um_State um_State { get; set; }
        public virtual um_User um_User { get; set; }
        public virtual um_User um_User1 { get; set; }
    }
}
