//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public um_Provider()
        {
            this.um_Practice_Provider_Patient_XREF = new HashSet<um_Practice_Provider_Patient_XREF>();
            this.um_Provider_Technicians_Xref = new HashSet<um_Provider_Technicians_Xref>();
            this.um_Provider_Documents = new HashSet<um_Provider_Documents>();
            this.ut_ExpensesLedger = new HashSet<ut_ExpensesLedger>();
        }
    
        public int Provider_ID { get; set; }
        public Nullable<long> Login_ID { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MI { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string BusinessName { get; set; }
        public string Payments { get; set; }
        public string Email { get; set; }
        public string LicenseNo { get; set; }
        public string IsLicenseVerified { get; set; }
        public string ProviderImage { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<decimal> FeeRange_From { get; set; }
        public Nullable<decimal> FeeRange_to { get; set; }
        public string Is_Contact_Info { get; set; }
        public string Full_name { get; set; }
        public Nullable<long> Provider_Practice_ID { get; set; }
        public Nullable<int> PatientEntries { get; set; }
        public string BillingCoponentAlert_Ind { get; set; }
        public Nullable<long> ProcessProvider_ID { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
        public Nullable<System.DateTime> verifiedon { get; set; }
        public Nullable<int> Verifiedby { get; set; }
        public Nullable<System.DateTime> LicenseExpirydate { get; set; }
        public Nullable<long> Account_ID { get; set; }
        public string Show_schedule { get; set; }
        public string Registeredin { get; set; }
        public string Debug_mode { get; set; }
        public string Driver_license { get; set; }
        public string Electrician_license { get; set; }
        public string Driver_license_customized { get; set; }
        public string Electrician_license_customized { get; set; }
        public string Phoneno_read_ind { get; set; }
        public string Refferalcode { get; set; }
        public string Activationcode { get; set; }
        public string Courtname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_Practice_Provider_Patient_XREF> um_Practice_Provider_Patient_XREF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_Provider_Technicians_Xref> um_Provider_Technicians_Xref { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_Provider_Documents> um_Provider_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_ExpensesLedger> ut_ExpensesLedger { get; set; }
    }
}
