//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_Patient_PersonalInfo_SHADOW
    {
        public int Patient_ID { get; set; }
        public Nullable<long> Login_ID { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MI { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string PatientEmail { get; set; }
        public string DrivingLicenceNo { get; set; }
        public Nullable<int> Patient_Status_ID { get; set; }
        public Nullable<System.DateTime> Registerdate { get; set; }
        public string SelfRegistered_Ind { get; set; }
        public Nullable<int> RegByUserRefType_ID { get; set; }
        public Nullable<int> RegByUserRef_ID { get; set; }
        public Nullable<long> RegByUserLogin_ID { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> Shadow_Date { get; set; }
        public string updatedFields { get; set; }
        public string Full_name { get; set; }
        public long Shadow_id { get; set; }
        public Nullable<long> Account_ID { get; set; }
    }
}
