//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_ReferenceTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public um_ReferenceTypes()
        {
            this.um_CreditCard_Transactions = new HashSet<um_CreditCard_Transactions>();
            this.um_CreditCard_Transactions1 = new HashSet<um_CreditCard_Transactions>();
            this.um_CreditCardInfo = new HashSet<um_CreditCardInfo>();
            this.ut_Addresses = new HashSet<ut_Addresses>();
            this.ut_Appointments = new HashSet<ut_Appointments>();
            this.ut_Appointments1 = new HashSet<ut_Appointments>();
            this.ut_Billing_Accounts = new HashSet<ut_Billing_Accounts>();
            this.ut_Billing_AccountsAggregation = new HashSet<ut_Billing_AccountsAggregation>();
            this.ut_Billing_AccountsAggregation1 = new HashSet<ut_Billing_AccountsAggregation>();
            this.ut_Billing_Admin_Transactions = new HashSet<ut_Billing_Admin_Transactions>();
            this.ut_Billing_Admin_Transactions1 = new HashSet<ut_Billing_Admin_Transactions>();
            this.ut_Billing_Custom_Fee_XREF = new HashSet<ut_Billing_Custom_Fee_XREF>();
            this.ut_Billing_Invoice = new HashSet<ut_Billing_Invoice>();
            this.ut_Billing_Invoice1 = new HashSet<ut_Billing_Invoice>();
            this.ut_Billing_InvoiceLineItems = new HashSet<ut_Billing_InvoiceLineItems>();
            this.ut_Billing_InvoiceLineItems1 = new HashSet<ut_Billing_InvoiceLineItems>();
            this.ut_Billing_ProviderPatient_Transactions = new HashSet<ut_Billing_ProviderPatient_Transactions>();
            this.ut_Billing_ProviderPatient_Transactions1 = new HashSet<ut_Billing_ProviderPatient_Transactions>();
        }
    
        public byte ReferenceType_ID { get; set; }
        public string ReferenceType { get; set; }
        public string Description { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_CreditCard_Transactions> um_CreditCard_Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_CreditCard_Transactions> um_CreditCard_Transactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_CreditCardInfo> um_CreditCardInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Addresses> ut_Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Appointments> ut_Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Appointments> ut_Appointments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_Accounts> ut_Billing_Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_AccountsAggregation> ut_Billing_AccountsAggregation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_AccountsAggregation> ut_Billing_AccountsAggregation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_Admin_Transactions> ut_Billing_Admin_Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_Admin_Transactions> ut_Billing_Admin_Transactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_Custom_Fee_XREF> ut_Billing_Custom_Fee_XREF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_Invoice> ut_Billing_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_Invoice> ut_Billing_Invoice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_InvoiceLineItems> ut_Billing_InvoiceLineItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_InvoiceLineItems> ut_Billing_InvoiceLineItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_ProviderPatient_Transactions> ut_Billing_ProviderPatient_Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_ProviderPatient_Transactions> ut_Billing_ProviderPatient_Transactions1 { get; set; }
    }
}
