//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Um_request_urls
    {
        public int Request_url_id { get; set; }
        public Nullable<int> Provider_id { get; set; }
        public string Fromaddress { get; set; }
        public string Toaddress { get; set; }
        public string Requested_Url { get; set; }
        public Nullable<System.DateTime> Requesteddate { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Status_ind { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> createdby { get; set; }
    }
}
