//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_State_SHADOW
    {
        public int State_ID { get; set; }
        public string State_Name { get; set; }
        public string State { get; set; }
        public string Abbrevation { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> Shadow_Date { get; set; }
        public string updatedFields { get; set; }
        public Nullable<long> County_ID { get; set; }
        public long Shadow_id { get; set; }
        public string IsPublicTherapist_Ind { get; set; }
    }
}
