//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_TopCities_Shadow
    {
        public Nullable<int> City_id { get; set; }
        public string City { get; set; }
        public string state { get; set; }
        public Nullable<int> State_ID { get; set; }
        public string State_Name { get; set; }
        public string DisplayInList_Ind { get; set; }
        public Nullable<System.DateTime> Shadow_Date { get; set; }
        public string UPdatedFields { get; set; }
        public long Shadow_id { get; set; }
    }
}
