//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_technician_Documents
    {
        public int TechnicianDocument_ID { get; set; }
        public Nullable<long> ProviderLogin_ID { get; set; }
        public Nullable<int> Provider_ID { get; set; }
        public Nullable<int> TechnicianID { get; set; }
        public Nullable<int> TechnicianLogin_ID { get; set; }
        public string Title { get; set; }
        public string DocDescription { get; set; }
        public string Path { get; set; }
        public string Path_Suffix { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string FileName { get; set; }
        public Nullable<long> Size_KB { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
        public string Displayinpublic { get; set; }
    }
}
