//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Um_Technician
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Um_Technician()
        {
            this.um_Provider_Technicians_Xref = new HashSet<um_Provider_Technicians_Xref>();
        }
    
        public int Technician_id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Phonenumber { get; set; }
        public string Status_ind { get; set; }
        public Nullable<System.DateTime> createon { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public string Self_ind { get; set; }
        public string Email { get; set; }
        public Nullable<int> Login_id { get; set; }
        public string Technician_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_Provider_Technicians_Xref> um_Provider_Technicians_Xref { get; set; }
    }
}
