//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Um_user_mobile_token
    {
        public int Mobiletoken_id { get; set; }
        public Nullable<int> Login_id { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> Mobile_session_timeout { get; set; }
        public string Status_ind { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public string mobileno { get; set; }
        public string IMEI_No { get; set; }
    }
}
