//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_User_SHADOW
    {
        public long Login_ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Encrypted_Password { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MI { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string NickName { get; set; }
        public Nullable<byte> RP_User_Ind { get; set; }
        public Nullable<bool> CognodeUser_Ind { get; set; }
        public string Is_Login { get; set; }
        public Nullable<int> NoOfRecords_Page { get; set; }
        public Nullable<System.DateTime> LastLogin_Date { get; set; }
        public Nullable<int> Login_Count { get; set; }
        public string IsLogin { get; set; }
        public string IsTherapyuser { get; set; }
        public Nullable<long> ther_id { get; set; }
        public string AllowCCCharges { get; set; }
        public Nullable<long> RegByLogin_ID { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> DefaultChargeCC_ID { get; set; }
        public Nullable<System.DateTime> Shadow_Date { get; set; }
        public string updatedFields { get; set; }
        public string IsTempPassword_Ind { get; set; }
        public string Full_Name { get; set; }
        public long Shadow_id { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
        public string Accesscode { get; set; }
        public Nullable<System.DateTime> Passwordrequestdate { get; set; }
        public Nullable<System.DateTime> Passwordrequesttime { get; set; }
        public Nullable<int> Defaultchargetype_id { get; set; }
    }
}
