//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public um_User()
        {
            this.um_Patient_PersonalInfo = new HashSet<um_Patient_PersonalInfo>();
            this.um_Practice_Provider_Patient_XREF = new HashSet<um_Practice_Provider_Patient_XREF>();
            this.um_Practice_Provider_Patient_XREF1 = new HashSet<um_Practice_Provider_Patient_XREF>();
            this.um_Provider_Documents = new HashSet<um_Provider_Documents>();
            this.um_SectionsInRole = new HashSet<um_SectionsInRole>();
            this.um_Provider_Technicians_Xref = new HashSet<um_Provider_Technicians_Xref>();
            this.ut_Addresses = new HashSet<ut_Addresses>();
            this.Um_users_notifications_info = new HashSet<Um_users_notifications_info>();
            this.um_UsersInRole = new HashSet<um_UsersInRole>();
            this.ut_Appointments = new HashSet<ut_Appointments>();
            this.ut_Appointments1 = new HashSet<ut_Appointments>();
            this.ut_Billing_Accounts = new HashSet<ut_Billing_Accounts>();
            this.ut_Billing_Admin_Transactions = new HashSet<ut_Billing_Admin_Transactions>();
            this.ut_Billing_Custom_Fee_XREF = new HashSet<ut_Billing_Custom_Fee_XREF>();
            this.ut_Billing_ProviderPatient_Transactions = new HashSet<ut_Billing_ProviderPatient_Transactions>();
            this.ut_Message_Reciever_XREF = new HashSet<ut_Message_Reciever_XREF>();
            this.ut_Message = new HashSet<ut_Message>();
        }
    
        public long Login_ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Encrypted_Password { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MI { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string NickName { get; set; }
        public Nullable<byte> RP_User_Ind { get; set; }
        public string Is_Login { get; set; }
        public Nullable<System.DateTime> LastLogin_Date { get; set; }
        public Nullable<int> Login_Count { get; set; }
        public string IsLogin { get; set; }
        public string AllowCCCharges { get; set; }
        public Nullable<long> RegByLogin_ID { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> DefaultChargeCC_ID { get; set; }
        public string IsTempPassword_Ind { get; set; }
        public string Full_Name { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
        public string Accesscode { get; set; }
        public Nullable<System.DateTime> Passwordrequestdate { get; set; }
        public Nullable<System.DateTime> Passwordrequesttime { get; set; }
        public Nullable<int> Defaultchargetype_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_Patient_PersonalInfo> um_Patient_PersonalInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_Practice_Provider_Patient_XREF> um_Practice_Provider_Patient_XREF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_Practice_Provider_Patient_XREF> um_Practice_Provider_Patient_XREF1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_Provider_Documents> um_Provider_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_SectionsInRole> um_SectionsInRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_Provider_Technicians_Xref> um_Provider_Technicians_Xref { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Addresses> ut_Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Um_users_notifications_info> Um_users_notifications_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<um_UsersInRole> um_UsersInRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Appointments> ut_Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Appointments> ut_Appointments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_Accounts> ut_Billing_Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_Admin_Transactions> ut_Billing_Admin_Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_Custom_Fee_XREF> ut_Billing_Custom_Fee_XREF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_ProviderPatient_Transactions> ut_Billing_ProviderPatient_Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Message_Reciever_XREF> ut_Message_Reciever_XREF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Message> ut_Message { get; set; }
    }
}
