//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Um_users_notifications_info
    {
        public int user_notification_info_id { get; set; }
        public long Login_ID { get; set; }
        public string Topic { get; set; }
        public string Token { get; set; }
        public string Status_ind { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public string MobileType { get; set; }
    
        public virtual um_User um_User { get; set; }
    }
}
