//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_verification_sites
    {
        public int Ver_id { get; set; }
        public string Category { get; set; }
        public string Siteurl { get; set; }
        public string Sitename { get; set; }
        public Nullable<int> State_id { get; set; }
        public string Statename { get; set; }
        public string Status_ind { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
    }
}
