//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_verification_users
    {
        public long verification_User_Id { get; set; }
        public Nullable<long> Account_ID { get; set; }
        public Nullable<long> Login_ID { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MI { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string Full_name { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> City_ID { get; set; }
        public Nullable<int> State_ID { get; set; }
        public string DCity_Name { get; set; }
        public string DState_Name { get; set; }
        public string DCountry_Name { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public string Zip { get; set; }
        public string CellPhone { get; set; }
        public string WorkPhone { get; set; }
        public string WorkPhoneExtn { get; set; }
        public string WorkPhoneLeaveMsg { get; set; }
        public string Fax { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> Loginhistory_id { get; set; }
        public string Gender { get; set; }
    }
}
