//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class um_zipcode1
    {
        public string ZIP_CODE { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTY_NAME { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public Nullable<int> City_id { get; set; }
        public Nullable<int> State_id { get; set; }
        public Nullable<int> County_id { get; set; }
        public string CountyName { get; set; }
        public long zipcode_id { get; set; }
    }
}
