//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ut_appointments_address
    {
        public int Appointment_address_id { get; set; }
        public Nullable<int> Provider_id { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> City_id { get; set; }
        public Nullable<int> State_id { get; set; }
        public Nullable<int> Country_id { get; set; }
        public string Zip { get; set; }
        public string City_name { get; set; }
        public string State_name { get; set; }
        public string Country_name { get; set; }
        public string Status_ind { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public string Court_location_name { get; set; }
        public string Default_address { get; set; }
    }
}
