//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_AppointmentReminder_Patients
    {
        public long AppointmentReminder_Patient_ID { get; set; }
        public Nullable<long> Patient_ID { get; set; }
        public Nullable<long> Provider_ID { get; set; }
        public Nullable<long> Appointment_ID { get; set; }
        public Nullable<int> Duration { get; set; }
        public string EmailSent_Ind { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> Updatedby { get; set; }
        public Nullable<long> EmailMessage_Transaction_ID { get; set; }
    }
}
