//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_appointment_requests
    {
        public int Appointmentrequest_id { get; set; }
        public Nullable<int> Appointment_id { get; set; }
        public Nullable<int> FromReferenceType_ID { get; set; }
        public Nullable<int> FromReference_ID { get; set; }
        public Nullable<int> FromReferenceLogin_ID { get; set; }
        public Nullable<int> ToReferenceLogin_ID { get; set; }
        public Nullable<int> ToReference_ID { get; set; }
        public Nullable<int> ToReferenceType_ID { get; set; }
        public Nullable<System.DateTime> Appointmentdate { get; set; }
        public Nullable<System.DateTime> appointmenttime { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Read_ind { get; set; }
        public string Status_ind { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
    }
}
