//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ut_appointments_messages_history
    {
        public int appt_msg_id { get; set; }
        public Nullable<int> appointment_id { get; set; }
        public Nullable<int> FromReferenceType_ID { get; set; }
        public Nullable<int> FromReference_ID { get; set; }
        public Nullable<int> FromReferenceLogin_ID { get; set; }
        public Nullable<int> ToReferenceLogin_ID { get; set; }
        public Nullable<int> ToReference_ID { get; set; }
        public Nullable<int> ToReferenceType_ID { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.DateTime> AppointmentTime { get; set; }
        public string Technician_ids { get; set; }
        public string Site_ind { get; set; }
        public string msg_ind { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string voice_IND { get; set; }
    }
}
