//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Billing_Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ut_Billing_Accounts()
        {
            this.ut_Billing_AccountsAggregation = new HashSet<ut_Billing_AccountsAggregation>();
            this.ut_Billing_AccountsAggregation1 = new HashSet<ut_Billing_AccountsAggregation>();
            this.ut_Billing_Admin_Transactions = new HashSet<ut_Billing_Admin_Transactions>();
            this.ut_Billing_Admin_Transactions1 = new HashSet<ut_Billing_Admin_Transactions>();
            this.ut_Billing_Invoice = new HashSet<ut_Billing_Invoice>();
            this.ut_Billing_Invoice1 = new HashSet<ut_Billing_Invoice>();
            this.ut_Billing_ProviderPatient_Transactions = new HashSet<ut_Billing_ProviderPatient_Transactions>();
            this.ut_Billing_ProviderPatient_Transactions1 = new HashSet<ut_Billing_ProviderPatient_Transactions>();
        }
    
        public long Account_ID { get; set; }
        public string AccountNo { get; set; }
        public Nullable<long> ReferenceLogin_ID { get; set; }
        public Nullable<int> Reference_ID { get; set; }
        public Nullable<byte> ReferenceType_ID { get; set; }
        public string OpeningBalanceType { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public string CurrentBalanceType { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public string AccountDescription { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual um_ReferenceTypes um_ReferenceTypes { get; set; }
        public virtual um_User um_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_AccountsAggregation> ut_Billing_AccountsAggregation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_AccountsAggregation> ut_Billing_AccountsAggregation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_Admin_Transactions> ut_Billing_Admin_Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_Admin_Transactions> ut_Billing_Admin_Transactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_Invoice> ut_Billing_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_Invoice> ut_Billing_Invoice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_ProviderPatient_Transactions> ut_Billing_ProviderPatient_Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Billing_ProviderPatient_Transactions> ut_Billing_ProviderPatient_Transactions1 { get; set; }
    }
}
