//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Billing_ProviderPatient_TransactionsDistribution_SHADOW
    {
        public int Distribution_ID { get; set; }
        public Nullable<int> Practice_ID { get; set; }
        public Nullable<long> ChargeTransaction_ID { get; set; }
        public Nullable<long> PaymentTransaction_ID { get; set; }
        public Nullable<System.DateTime> DistributedOn { get; set; }
        public Nullable<decimal> AppliedAmount { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> Shadow_Date { get; set; }
        public string updatedFields { get; set; }
        public long Shadow_id { get; set; }
        public Nullable<long> Loginhistory_id { get; set; }
    }
}
