//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Billing_Invoice_SHADOW
    {
        public int Invoice_ID { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceType { get; set; }
        public string RecieptNo { get; set; }
        public Nullable<long> FromAccount_ID { get; set; }
        public Nullable<int> FromReference_ID { get; set; }
        public Nullable<byte> FromReferenceType_ID { get; set; }
        public Nullable<int> ToReference_ID { get; set; }
        public Nullable<byte> ToReferenceType_ID { get; set; }
        public Nullable<long> ToAccount_ID { get; set; }
        public Nullable<int> Practice_ID { get; set; }
        public Nullable<System.DateTime> Begin_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public Nullable<decimal> InvoiceCharges { get; set; }
        public Nullable<decimal> InvoicePayments { get; set; }
        public Nullable<decimal> InvoicePosAdjstmnts { get; set; }
        public Nullable<decimal> InvoiceNegAdjstmnts { get; set; }
        public Nullable<decimal> PrevBalance { get; set; }
        public Nullable<decimal> PrevAdvance { get; set; }
        public Nullable<decimal> InvoiceBalance { get; set; }
        public string CCPaymentProcess { get; set; }
        public Nullable<decimal> SalesTax_Amount { get; set; }
        public Nullable<long> ServiceTaxTransaction_ID { get; set; }
        public Nullable<int> Previous_Invoice_ID { get; set; }
        public string MesssetoUser { get; set; }
        public string TermsAndConditions { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> Shadow_Date { get; set; }
        public string updatedFields { get; set; }
        public long Shadow_id { get; set; }
        public Nullable<long> Provider_id { get; set; }
    }
}
