//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Billing_InvoiceLineItems_SHADOW
    {
        public int ChargeLineItem_ID { get; set; }
        public int Invoice_ID { get; set; }
        public long ChargeTransaction_ID { get; set; }
        public Nullable<int> FromReference_ID { get; set; }
        public Nullable<byte> FromReferenceType_ID { get; set; }
        public Nullable<int> ToReference_ID { get; set; }
        public Nullable<byte> ToReferenceType_ID { get; set; }
        public Nullable<int> Practice_ID { get; set; }
        public Nullable<byte> TransactionType_ID { get; set; }
        public Nullable<int> BillingService_ID { get; set; }
        public Nullable<int> BillingChargeType_ID { get; set; }
        public Nullable<System.DateTime> Charge_Date { get; set; }
        public Nullable<decimal> AmountCharged { get; set; }
        public Nullable<decimal> ServiceTaxAmount { get; set; }
        public Nullable<double> ServiceTaxPercentage { get; set; }
        public Nullable<int> ReferenceBillingService_ID { get; set; }
        public string ReferenceBillingService { get; set; }
        public string InvoiceGenerated_Ind { get; set; }
        public string ChargeNotes { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> Shadow_Date { get; set; }
        public string updatedFields { get; set; }
        public long Shadow_id { get; set; }
        public Nullable<long> Provider_id { get; set; }
    }
}
