//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Billing_ProviderPatient_ChequeTransactions
    {
        public int ChequeTransaction_ID { get; set; }
        public long Transaction_ID { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string IssuedBankName { get; set; }
        public decimal ChequeAmount { get; set; }
        public string Status_Ind { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> Loginhistory_id { get; set; }
    
        public virtual ut_Billing_ProviderPatient_Transactions ut_Billing_ProviderPatient_Transactions { get; set; }
    }
}
