//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_ClientEventInfo_Log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ut_ClientEventInfo_Log()
        {
            this.ut_Client_BasicInfo_Log = new HashSet<ut_Client_BasicInfo_Log>();
            this.ut_Patient_Notesinfo_Log = new HashSet<ut_Patient_Notesinfo_Log>();
            this.ut_Provider_Info_Log = new HashSet<ut_Provider_Info_Log>();
        }
    
        public int EventInfoLog_ID { get; set; }
        public Nullable<int> EventCategory_ID { get; set; }
        public Nullable<int> GoalEventtype_ID { get; set; }
        public Nullable<long> ClientLogin_ID { get; set; }
        public Nullable<int> EventReference_ID { get; set; }
        public string Title { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual um_ClientEvent_Category um_ClientEvent_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Client_BasicInfo_Log> ut_Client_BasicInfo_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Patient_Notesinfo_Log> ut_Patient_Notesinfo_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Provider_Info_Log> ut_Provider_Info_Log { get; set; }
    }
}
