//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Component_CreditCard_Expiry
    {
        public long ExpiryLog_ID { get; set; }
        public Nullable<long> Reference_ID { get; set; }
        public Nullable<long> ReferenceLogin_ID { get; set; }
        public string ProcessedBillingService_ID { get; set; }
        public Nullable<long> CCDetails_ID { get; set; }
        public string EmailID { get; set; }
        public string M_Subject { get; set; }
        public string M_Body { get; set; }
        public string IsSent { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public string Status_ind { get; set; }
        public Nullable<long> ProcessProvider_ID { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
    
        public virtual ut_BillingComponent_ProcesstoProvider ut_BillingComponent_ProcesstoProvider { get; set; }
    }
}
