//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_creditcard_refundservice_transactions
    {
        public int ccrefundservicetrans_id { get; set; }
        public Nullable<int> Transaction_id { get; set; }
        public Nullable<System.DateTime> Tran_date { get; set; }
        public Nullable<int> Fromreference_id { get; set; }
        public string Fromusername { get; set; }
        public Nullable<int> Fromreferencetype_id { get; set; }
        public string Fromusertype { get; set; }
        public Nullable<int> Toreference_id { get; set; }
        public string Tousername { get; set; }
        public Nullable<int> Toreferencetype_id { get; set; }
        public string Posted_data { get; set; }
        public string InvoiceNum { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> RefundedAmount { get; set; }
        public string CCNumber { get; set; }
        public Nullable<int> CreditCardType_ID { get; set; }
        public string CVV2 { get; set; }
        public string CardHolderName { get; set; }
        public Nullable<byte> CardExpiryMonth { get; set; }
        public Nullable<short> CardExpiryYear { get; set; }
        public string BillingAddress_1 { get; set; }
        public string BillingAddress_2 { get; set; }
        public Nullable<int> BillingCity_ID { get; set; }
        public string city { get; set; }
        public Nullable<int> BillingState_ID { get; set; }
        public string state { get; set; }
        public Nullable<int> BillingCountry_ID { get; set; }
        public string country { get; set; }
        public string BillingZIP { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<bool> ManualTransaction_Ind { get; set; }
        public Nullable<int> TransactionNoRef_ID { get; set; }
        public Nullable<int> TransactionNoRefType_ID { get; set; }
        public Nullable<long> ParentTransaction_ID { get; set; }
        public string IsRefundable_Ind { get; set; }
        public string Status_code { get; set; }
        public Nullable<long> RefPatientLogin_ID { get; set; }
        public Nullable<int> PaymentTransID { get; set; }
        public string CCtype { get; set; }
        public string trans_type { get; set; }
        public Nullable<int> referType_id { get; set; }
        public string Is_runned { get; set; }
        public Nullable<int> Sequence_number { get; set; }
        public string Status_ind { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public string Issccfailed_ind { get; set; }
        public Nullable<int> practice_id { get; set; }
        public string paypalsaletransactionid { get; set; }
        public string Email_sent { get; set; }
        public Nullable<long> Provider_id { get; set; }
    }
}
