//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_ComponentJob_Error_XREF_SHADOW
    {
        public int Component_Error_ID { get; set; }
        public Nullable<int> Component_ID { get; set; }
        public Nullable<int> ComponentJobstatus_Id { get; set; }
        public Nullable<int> Project_ID { get; set; }
        public string ErrASPCode { get; set; }
        public string ErrNumber { get; set; }
        public string Exception_Name { get; set; }
        public string ErrSource { get; set; }
        public string ErrCategory { get; set; }
        public string ErrFile { get; set; }
        public string ErrLine { get; set; }
        public string ErrColumn { get; set; }
        public string ErrDescription { get; set; }
        public string ErrAspDescription { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> Class_ID { get; set; }
        public Nullable<int> Method_ID { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> Shadow_Date { get; set; }
        public string updatedFields { get; set; }
        public long Shadow_id { get; set; }
    }
}
