//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ut_class_method_runtime
    {
        public int Runtime_id { get; set; }
        public Nullable<int> Provider_id { get; set; }
        public string Class_name { get; set; }
        public string Method_name { get; set; }
        public Nullable<System.DateTime> Startruntime { get; set; }
        public Nullable<System.DateTime> Endruntime { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public string Mobile_type { get; set; }
    }
}
