//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_EmailMessage_Transactions
    {
        public long EmailMessage_Transaction_ID { get; set; }
        public Nullable<int> EmailMessage_Option_ID { get; set; }
        public Nullable<int> FromReference_ID { get; set; }
        public Nullable<int> FromReferenceType_ID { get; set; }
        public Nullable<int> ToRefernce_ID { get; set; }
        public string ToReferenceType_ID { get; set; }
        public Nullable<int> Practice_ID { get; set; }
        public string Mail_From { get; set; }
        public string Mail_To { get; set; }
        public string Cc { get; set; }
        public string Bcc { get; set; }
        public string Subject { get; set; }
        public string Message_Body { get; set; }
        public Nullable<System.DateTime> Mail_GeneratedDate { get; set; }
        public string AlternateEmail { get; set; }
        public string Transaction_Type { get; set; }
        public string Isusernamesent_Ind { get; set; }
        public string IsPwrdsent_Ind { get; set; }
        public Nullable<int> EmailStatus_Id { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UPdatedOn { get; set; }
        public Nullable<long> Appointment_ID { get; set; }
        public Nullable<System.DateTime> Appointment_Date { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
        public Nullable<long> Provider_id { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Reminderstatus_id { get; set; }
        public Nullable<long> Appointment_Duration { get; set; }
    }
}
