//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_ExpensesLedger
    {
        public int Exp_Ledger_ID { get; set; }
        public Nullable<int> Practice_ID { get; set; }
        public Nullable<int> Provider_ID { get; set; }
        public Nullable<int> Exp_Category_ID { get; set; }
        public Nullable<System.DateTime> Exp_Date { get; set; }
        public string Item { get; set; }
        public string Quantity { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string CheckNumber { get; set; }
        public string Vendor { get; set; }
        public Nullable<int> Deductible { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
        public string Image_file { get; set; }
    
        public virtual um_Provider um_Provider { get; set; }
    }
}
