//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Forum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ut_Forum()
        {
            this.ut_ForumTopic = new HashSet<ut_ForumTopic>();
            this.ut_ForumTopic1 = new HashSet<ut_ForumTopic>();
        }
    
        public int Forum_ID { get; set; }
        public string ForumName { get; set; }
        public string Message { get; set; }
        public Nullable<long> Login_ID { get; set; }
        public string Public_Ind { get; set; }
        public string ReadTopicsPosts { get; set; }
        public string PostNewTopics { get; set; }
        public string PostNewReplies { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public string ModeratorForum_Ind { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_ForumTopic> ut_ForumTopic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_ForumTopic> ut_ForumTopic1 { get; set; }
    }
}
