//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ut_FAQ_Question_category_Xref
    {
        public int Question_category_id { get; set; }
        public Nullable<long> Question_Id { get; set; }
        public Nullable<int> Category_id { get; set; }
        public string Category_name { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
    
        public virtual Um_FAQ_Categories Um_FAQ_Categories { get; set; }
        public virtual Um_FAQ_Questions Um_FAQ_Questions { get; set; }
    }
}
