//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Login_History
    {
        public int LoginHistory_ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> Login_ID { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> Project_ID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<bool> CookieEnabled_Ind { get; set; }
        public Nullable<bool> JavaEnabled_Ind { get; set; }
        public Nullable<bool> Online_Ind { get; set; }
        public string UserAgent { get; set; }
        public string UserLanguage { get; set; }
        public Nullable<System.DateTime> LogIn_DateTime { get; set; }
        public Nullable<System.DateTime> LogOut_DateTime { get; set; }
        public Nullable<bool> LoginSuccess_Ind { get; set; }
        public string IsRequestforPwrd { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string State { get; set; }
        public string city { get; set; }
        public string Zip { get; set; }
        public string Mobile_type { get; set; }
        public string Deviceaddress { get; set; }
        public string Devicephonenumber { get; set; }
    }
}
