//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Message_Reciever_XREF
    {
        public int Message_Reciever_ID { get; set; }
        public Nullable<int> Message_ID { get; set; }
        public Nullable<long> Sender_ID { get; set; }
        public Nullable<long> Reciever_ID { get; set; }
        public Nullable<long> RecieverPractice_ID { get; set; }
        public string Read_Ind { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Archive_Ind { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public string Sentarchive_ind { get; set; }
    
        public virtual um_User um_User { get; set; }
        public virtual ut_Message ut_Message { get; set; }
    }
}
