//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_MessageCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ut_MessageCategory()
        {
            this.ut_Message = new HashSet<ut_Message>();
            this.ut_Message_RelatedRoles = new HashSet<ut_Message_RelatedRoles>();
            this.ut_MessageCategoryInRole = new HashSet<ut_MessageCategoryInRole>();
        }
    
        public int MessageCategory_ID { get; set; }
        public string MessageCategory { get; set; }
        public string SysGenMsgs_Ind { get; set; }
        public string UserGenMsgs_Ind { get; set; }
        public string Filepath { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Message> ut_Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Message_RelatedRoles> ut_Message_RelatedRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_MessageCategoryInRole> ut_MessageCategoryInRole { get; set; }
    }
}
