//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ut_Message()
        {
            this.ut_Message_Reciever_XREF = new HashSet<ut_Message_Reciever_XREF>();
            this.ut_MsgAttachFilename = new HashSet<ut_MsgAttachFilename>();
        }
    
        public int Message_ID { get; set; }
        public Nullable<long> Sender_ID { get; set; }
        public string Subject { get; set; }
        public string Messagebody { get; set; }
        public Nullable<int> MsgCategory_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<int> Provider_ID { get; set; }
        public Nullable<long> Practice_ID { get; set; }
        public Nullable<int> Reply_ID { get; set; }
        public string MsgLevel { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Archive_Ind { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public Nullable<long> BillingServicesComapny_ID { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
    
        public virtual um_User um_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Message_Reciever_XREF> ut_Message_Reciever_XREF { get; set; }
        public virtual ut_MessageCategory ut_MessageCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_MsgAttachFilename> ut_MsgAttachFilename { get; set; }
    }
}
