//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_mobileowner_data
    {
        public int Mobileowner_id { get; set; }
        public string AllCellInfo { get; set; }
        public string CallState { get; set; }
        public string CellLocation { get; set; }
        public string DataActivity { get; set; }
        public string DataState { get; set; }
        public string DeviceId { get; set; }
        public string DeviceSoftwareVersion { get; set; }
        public string GroupIdLevel1 { get; set; }
        public string Handle { get; set; }
        public string HasIccCard { get; set; }
        public string IsNetworkRoaming { get; set; }
        public string MmsUAProfUrl { get; set; }
        public string MmsUserAgent { get; set; }
        public string NeighboringCellInfo { get; set; }
        public string NetworkCountryIso { get; set; }
        public string NetworkOperator { get; set; }
        public string NetworkOperatorName { get; set; }
        public string NetworkType { get; set; }
        public string PhoneType { get; set; }
        public string SimCountryIso { get; set; }
        public string SimOperator { get; set; }
        public string SimOperatorName { get; set; }
        public string SimSerialNumber { get; set; }
        public string SimState { get; set; }
        public string SubscriberId { get; set; }
        public string VoiceMailAlphaTag { get; set; }
        public string VoiceMailNumber { get; set; }
        public string deviceownername { get; set; }
        public string deviceadderessMaxline { get; set; }
        public string deviceaddress { get; set; }
        public string devicePhone { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string Mobile_type { get; set; }
    }
}
