//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Message_RelatedRoles
    {
        public int MR_ID { get; set; }
        public Nullable<byte> Role_ID { get; set; }
        public Nullable<byte> Role_Related_ID { get; set; }
        public string DisplayName { get; set; }
        public string View_Ind { get; set; }
        public string SendUserLevel_Ind { get; set; }
        public string SendGroupLevel_Ind { get; set; }
        public Nullable<int> MessageCategory_ID { get; set; }
        public string Status_Ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> Loginhistory_ID { get; set; }
    
        public virtual um_Role um_Role { get; set; }
        public virtual um_Role um_Role1 { get; set; }
        public virtual ut_MessageCategory ut_MessageCategory { get; set; }
    }
}
