//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Provider_Info_Log
    {
        public long Provider_Info_ID { get; set; }
        public Nullable<int> EventInfoLog_ID { get; set; }
        public Nullable<long> ProviderLogin_id { get; set; }
        public string Field { get; set; }
        public string PreviousValue { get; set; }
        public string Presentvalue { get; set; }
        public string Status_ind { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<long> Createdby { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public Nullable<long> Updatedby { get; set; }
    
        public virtual ut_ClientEventInfo_Log ut_ClientEventInfo_Log { get; set; }
    }
}
