//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Provider_MobileStatistic
    {
        public int Listing_Statistic_ID { get; set; }
        public byte SiteStatic_ID { get; set; }
        public Nullable<int> Provider_ID { get; set; }
        public Nullable<long> ProviderLogin_ID { get; set; }
        public Nullable<int> Practice_ID { get; set; }
        public Nullable<int> YearValue { get; set; }
        public Nullable<int> MonthValue { get; set; }
        public Nullable<int> ViewedCount { get; set; }
        public string Status_IND { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<byte> UpdatedBy { get; set; }
        public Nullable<int> Childwebsite_ID { get; set; }
        public Nullable<long> Reference_ID { get; set; }
        public Nullable<long> ViewFrom_State_ID { get; set; }
        public Nullable<long> ViewFrom_City_ID { get; set; }
        public string State_Name { get; set; }
        public string City_Name { get; set; }
        public Nullable<long> State_ID { get; set; }
        public Nullable<long> City_ID { get; set; }
    }
}
