//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ut_SentEmails_Log
    {
        public long EmailLog_ID { get; set; }
        public Nullable<int> EmailMessage_Category_ID { get; set; }
        public Nullable<int> CatCount { get; set; }
        public Nullable<long> FromReference_id { get; set; }
        public Nullable<long> Toreference_id { get; set; }
        public string ISWebService_IND { get; set; }
        public Nullable<int> Application_Id { get; set; }
        public string Status_ind { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> Fromreferencetype_id { get; set; }
        public Nullable<int> Toreferencetype_id { get; set; }
    
        public virtual um_EmailMessage_Categoires um_EmailMessage_Categoires { get; set; }
    }
}
