//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ut_Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ut_Tasks()
        {
            this.ut_Task_Actionitems = new HashSet<ut_Task_Actionitems>();
        }
    
        public int Task_id { get; set; }
        public Nullable<int> Referencetype_id { get; set; }
        public Nullable<int> Reference_id { get; set; }
        public Nullable<System.DateTime> Taskdate { get; set; }
        public string Tasktitle { get; set; }
        public Nullable<System.DateTime> Duedate { get; set; }
        public string Isdone { get; set; }
        public string Notes { get; set; }
        public string Status_ind { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string DisplayInshedule_Ind { get; set; }
        public Nullable<long> LoginHistory_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ut_Task_Actionitems> ut_Task_Actionitems { get; set; }
    }
}
