//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ut_trial_package_users
    {
        public int Trialpkguser_id { get; set; }
        public Nullable<int> Login_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> Nextrenewdate { get; set; }
        public string status_ind { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
    }
}
