//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Appointments
    {
        public int Appointment_ID { get; set; }
        public Nullable<int> Practice_ID { get; set; }
        public Nullable<byte> FromReferencetype_ID { get; set; }
        public int FromReference_ID { get; set; }
        public long FromReferenceLogin_ID { get; set; }
        public Nullable<long> ToReferenceLogin_ID { get; set; }
        public Nullable<int> ToReference_ID { get; set; }
        public Nullable<byte> ToReferenceType_ID { get; set; }
        public Nullable<int> FacilityReference_ID { get; set; }
        public Nullable<byte> AppointmentType_ID { get; set; }
        public Nullable<int> CurrentAppointmentTracking_ID { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.DateTime> AppointmentTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Notes { get; set; }
        public Nullable<byte> AppointmentStatus_ID { get; set; }
        public string AppointmentStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string AppointmentBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Status_Ind { get; set; }
        public string Technician_ids { get; set; }
        public string Tech_pos_mobile { get; set; }
        public Nullable<int> AppointmentRecurrence_ID { get; set; }
        public Nullable<byte> IntervalType_ID { get; set; }
        public Nullable<int> IntervalValue { get; set; }
        public Nullable<int> NumofOccurrences { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string SelectedWeekdays { get; set; }
        public string notes_voice_filename { get; set; }
        public string placeofservice { get; set; }
        public Nullable<int> Appointment_address_id { get; set; }
    }
}
