//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Patient_PatientDetails
    {
        public Nullable<long> Login_ID { get; set; }
        public int Patient_ID { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MI { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> City_ID { get; set; }
        public string City { get; set; }
        public Nullable<int> State_ID { get; set; }
        public string State { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public string Country { get; set; }
        public string ZIP { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string CellPhone { get; set; }
        public string PrimaryAddress_Ind { get; set; }
        public string DrivingLicenceNo { get; set; }
        public Nullable<int> Patient_Status_ID { get; set; }
    }
}
